### ISSUE TITLE
IDE plug-in is out-of-date

### ISSUE THREAD

**Issue by DennisMerritt** [AmziLS/AmziProlog#27]
The Amzi! plug-in for Eclipse is out-of-date and brittle.  It currently builds the plug-in on my Mac computer, but, for example, doesn't build under Windows.  I don't know why.  It also fails to build the stand-alone version of the Amzi! development environment, although it used to.  I'm not sure what's changed.  I'm looking for someone who understands Eclipse RCP development to get this project building smoothly on current versions of Eclipse.

(The old version, distributed with the 9.x release of Amzi!, works fine.  The problem is rebuilding it.)
--Dennis

**Comment by maelh** [comment]
Updated and fixed many errors and warnings. There are still quite a few left, but they aren't critical and mostly about deprecated features/classes. Replacing them may brake things, so it's best to do this after a working release was built.

**Comment by maelh** [comment]
IDE plugin is fully functional again. (Some warnings are left.)
