### ISSUE TITLE
Linux Installation -- requesting clarifications

### ISSUE THREAD

**Issue by claudiosa** [AmziLS/AmziProlog#6]
Hi everyone

I follow the instructions to install the AMZI by  a makefile from Centos. The instructions that I followed are from:
https://github.com/AmziLS/apls/blob/master/devdocs/amzi_build.md
including a directory under /opt/amzi/apls ... et all.
I tried to do it as superuser (root). For 3 times, this makefile corrupted my system in /bin and /usr/bin , probably some warning should be include in that Makefile suggested: "do not use it as root" or something like that.

Well, in addition, could you provide a installation step-by-step, once that some variables from this make is unclear
see these lines:
..................................
SOURCE=$(APLS_SOURCE)
SUBDIRS = engine run link listen compile
RELEASE=$(APLS_RELEASE)
.................................
Normally, in SOURCE cames the path where the files to be compiled ...
if I did a clone of apls in /opt/amzi/
whose are the contents for APLS_SOURCE and APLS_RELEASE?
Well, someone can help me in this installation under any Linux?

Claudio

**Comment by DennisMerritt** [comment]
It’s been a long time since I built the system on Linux.  It was on CentOS 64.  I don’t remember enough to be able to help, maybe someone else out there?

—Dennis

**Comment by claudiosa** [comment]
Thank you Dennis
